version: '3'
services: 
    svc_gateway:
        image: meongbego/svc_gateway
        restart: always
        ports:
            - 80:80
        environment:
            - GIN_MODE=release
            - SERVER_ADDRESS=0.0.0.0
            - SERVER_PORT=80
            - SERVER_TIMEZONE=Asia/Jakarta
            - KAFKA_HOST=localhost
            - KAFKA_PORT=9092
            - SWAGGER_SERVER_ADDRESS=http://0.0.0.0
            - LOGGER_URL=logger:3000
        command: ./main -e production
        depends_on:
            - zookeeper
            - logger
            - broker
  