version: "3"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
    networks:
      choreo_net:
          aliases:
          - jaeger
  kraken_designer:
    image: devopsfaith/krakendesigner:latest
    ports:
      - 8787:80
    networks:
      choreo_net:
          aliases:
          - kraken_designer
  krakend_ce:
    image: devopsfaith/krakend:1.1.1
    volumes:
      - ./etc/:/etc/krakend
    ports:
      - "1234:1234"
      - "8080:8080"
      - "8090:8090"
    depends_on:
      - jaeger
    networks:
      choreo_net:
          aliases:
          - krakend_ce
networks:
  choreo_net:
      driver: bridge