version: "3.2"
services:
    database_1:
        container_name: database_1
        image: cockroachdb/cockroach:latest
        volumes:
        - ./data/database/node_1:/cockroach/cockroach-data
        command: start --insecure
        ports:
        - "26257:26257"

    database_2:
        container_name: database_2
        image: cockroachdb/cockroach:latest
        volumes:
        - ./data/database/node_2:/cockroach/cockroach-data
        command: start --insecure --join=database_1
        ports:
        - "26258:26257"

    order_1:
        container_name: order_1
        image: cockroachdb/cockroach:latest
        volumes:
        - ./data/database/order_1:/cockroach/cockroach-data
        command: start --insecure
        ports:
        - "26259:26257"
        - "8081:8080"
    order_2:
        container_name: order_2
        image: cockroachdb/cockroach:latest
        volumes:
        - ./data/database/order_2:/cockroach/cockroach-data
        command: start --insecure --join=order_2
        ports:
        - "26260:26257"

    payment_1:
        container_name: payment_1
        image: cockroachdb/cockroach:latest
        volumes:
        - ./data/database/payment_1:/cockroach/cockroach-data
        command: start --insecure
        ports:
        - "26261:26257"
        - "8082:8080"
    payment_2:
        container_name: payment_2
        image: cockroachdb/cockroach:latest
        volumes:
        - ./data/database/payment_2:/cockroach/cockroach-data
        command: start --insecure --join=payment_2
        ports:
        - "26262:26257"

    mongo:
        image: mongo
        ports:
        - 27017:27017
        volumes:
        - ./data/mongo:/data/db
    jaeger:
        image: jaegertracing/all-in-one:latest
        ports:
            - "16686:16686"
            - "14268:14268"
    logger:
        image: meongbego/cinlog
        restart: always
        ports:
            - 3000:3000
        environment:
            - GIN_MODE=release
            - SERVER_ADDRESS=0.0.0.0
            - SERVER_PORT=3000
            - SERVER_TIMEZONE=Asia/Jakarta
            - MONGO_HOST=mongo
            - MONGO_PORT=27017
            - MONGO_DATABASE=logger
            - MONGO_USER=
            - MONGO_PASSWORD=
            - LOGGER_DRIVER=mongo
        command: ./main -e production
        depends_on:
            - mongo

    orch_user:
        image: meongbego/orch_user
        restart: always
        ports:
            - 81:80
        environment:
            - GIN_MODE=release
            - SERVER_ADDRESS=0.0.0.0
            - SERVER_PORT=80
            - SERVER_TIMEZONE=Asia/Jakarta
            - APP_NAME=gateway
            - KAFKA_HOST=broker
            - KAFKA_PORT=9092
            - SWAGGER_SERVER_ADDRESS=http://0.0.0.0
            - LOGGER_URL=logger:3000
        command: ./main -e production
        depends_on:
            - database_1
            - database_2
            - logger
    orch_order:
        image: meongbego/orch_order
        restart: always
        ports:
            - 82:80
        environment:
            - GIN_MODE=release
            - SERVER_ADDRESS=0.0.0.0
            - SERVER_PORT=80
            - SERVER_TIMEZONE=Asia/Jakarta
            - APP_NAME=gateway
            - KAFKA_HOST=broker
            - KAFKA_PORT=9092
            - SWAGGER_SERVER_ADDRESS=http://0.0.0.0
            - LOGGER_URL=logger:3000
        command: ./main -e production
        depends_on:
            - order_1
            - order_2
            - logger
    orch_payment:
        image: meongbego/orch_payment
        restart: always
        ports:
            - 83:80
        environment:
            - GIN_MODE=release
            - SERVER_ADDRESS=0.0.0.0
            - SERVER_PORT=80
            - SERVER_TIMEZONE=Asia/Jakarta
            - APP_NAME=gateway
            - KAFKA_HOST=broker
            - KAFKA_PORT=9092
            - SWAGGER_SERVER_ADDRESS=http://0.0.0.0
            - LOGGER_URL=logger:3000
        command: ./main -e production
        depends_on:
            - payment_1
            - payment_2
            - logger
    orchestrator:
        image: meongbego/orchestrator
        restart: always
        ports:
            - 80:80
        environment:
            - GIN_MODE=release
            - SERVER_ADDRESS=0.0.0.0
            - SERVER_PORT=80
            - SERVER_TIMEZONE=Asia/Jakarta
            - APP_NAME=gateway
            - KAFKA_HOST=broker
            - KAFKA_PORT=9092
            - SWAGGER_SERVER_ADDRESS=http://0.0.0.0
            - LOGGER_URL=logger:3000
        command: ./main -e production
        depends_on:
            - zookeeper
            - logger
            - broker
            - svc_order
            - svc_payment
            - svc_user
    
    krakend_ce:
        image: devopsfaith/krakend:1.1.1
        volumes:
            - ../krakend/etc/:/etc/krakend
        ports:
            - "1234:1234"
            - "8080:8080"
            - "8090:8090"
        depends_on:
            - jaeger
            - api
    kraken_designer:
        image: devopsfaith/krakendesigner:latest
        ports:
            - 8787:80

    